[package]
name = "weather_reporting"
version = "0.1.0"
authors = ["corka149 <corka149@mailbox.org>"]

[dependencies]
chrono = "0.4"
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.9.0"
